= nng-wolfssl

This package is meant for use as a plugin for
http://github.com/nanomsg/nng[NNG], providing support for
TLS v1.0 and newer via the https://wolfssl.com[wolfSSL] library.

NOTE: This plugin is not sponsored or endorsed by the makers of wolfSSL.

The main benefits of using wolfSSL over other alternatives lie in
support for modern TLSv1.3 with commercial support, and an optional
FIPS 140-2 compliant solution.

== Configuration

This plugin should already be a Git submodule within the
NNG installation, at the right location.

Download and install wolfSSL as per the instructions.
This library will attempt to locate the installation in the
usual places.  If a different value for `--prefix` was
specified, then it may be necessary to supply that to
CMake using `-DWOLFSSL_ROOT_DIR=_prefix_`.

You can find open source for wolfSSL on
https://github.com/wolfssl/wolfssl[GitHub].
(Commercial users should use the version supplied by wolfSSL.)

The default configuration of wolfSSL leaves out many useful
features, such as CRLs, encrypted private key files, as well as
older (but still widely used) versions of TLS and some algorithms.

This plugin will attempt to discover what options are present

== Limitations and Caveats

* wolfSSL does not have any support for reporting the verification
  status of peer certificates when `NNG_TLS_AUTH_MODE_OPTIONAL` is
  used.

* wolfSSL always supports the newest version(s) of TLS 1.3, without
  any ability to disable such support.

* PSK (pre-shared keys) ciphersuites are not supported.

* Only TLS 1.0 and newer is supported, and only if configured
  in the wolfSSL library itself.

* Session resumption is not supported.

* Session renegotiation is not supported.  (Removed in TLS v1.3.)

* Compression is not supported.  (Removed in TLS v1.3.)

* 0-RTT is not supported.

* FIPS mode is not supported in this free version.

== License

This plugin is licensed under the Gnu Public License (GPL)
version 3.0.
User's wishing to use this in settings incompatible with that
license may purchase a commercial license from
https://www.staysail.tech[Staysail Systems, Inc.]

== Contact

Please contact the developers about any further questions
with respect to this product at mailto:info@staysail.tech[].

== Copyright

Copyright 2020 Staysail Systems, Inc.